name = "StringManipulation"
uuid = "892a3eda-7b42-436c-8928-eab12a02cf0e"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.4.2"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "^1.10"
PrecompileTools = "1"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Markdown"]
